### ISSUE TITLE
When mounting root component, mount through ReactReconciler.mountComponent() instead of calling component.mountComponent() directly

### ISSUE THREAD

**Issue by finnigantime** [iamdustan/tiny-react-renderer#11]
Great project.

When trying to use as a template to build a renderer (targeting React v15.2.0), I hit an issue with this code in mount.js:

```
      component.mountComponent(
        transaction,
        rootId,
        {_idCounter: 0},
        {}
      );
```

The issue I hit is: "Warning: ReactComponentTreeDevtool: Missing React element for debugID 1 when building stack"

I was able to fix this by rewriting the above as:

```
      ReactReconciler.mountComponent(
        component,
        transaction,
        rootId,
        {_idCounter: 0},
        {}
      );
```

This is necessary because ReactReconciler.mountComponent wraps component.mountComponent and before calling it runs:

```
        ReactInstrumentation.debugTool.onBeforeMountComponent(
          internalInstance._debugID,
          internalInstance._currentElement
        );
```

Which starts tracking the root React component in the debugTool.

**Comment by iamdustan** [comment]
Awesome! Thanks @finnigantime. I knew I had some updates to make for React 15.2. We’re in our final sprint before product launch at work so it’ll likely take me a week or so to follow up on this. I’ll _try_ to get to it earlier, but no promises.

**Comment by finnigantime** [comment]
Sounds good! Yeah I notice there are a few signatures that should change with 15.2.

For this PR I put up for this issue in particular, I kept the pre-15.2 signature so it should be good to go before you update the rest of the project. Let me know if I should run any particular test first.

**Comment by iamdustan** [comment]
Closing since the stack version is no longer maintained.
