### ISSUE TITLE
Possible bug in src/component.js

### ISSUE THREAD

**Issue by jem-computer** [iamdustan/tiny-react-renderer#20]
Hey! This repo is fantastic, thank you so much.

Everything is still melting my brain so I don't feel comfortable submitting a PR just yet, but I think I've found a bug.
https://github.com/iamdustan/tiny-react-renderer/blob/master/src/component.js#L140

this.node.children always seems to be null for me - not sure if that's a change to internals since this repo was last updated, or a typo. `this.updateChildren` indeed uses `nextElement.props.children` rather than `nextElement.children`.
```diff
  mountComponent(
    transaction,
    nativeParent,
    nativeContainerInfo,
    context
  ) {
    this.node = this._currentElement;
-    this.mountChildren(this.node.children, transaction, context);
+    this.mountChildren(this.node.props.children, transaction, context);
    return this.node;
  },

  receiveComponent(nextElement, transaction, context) {
    const prevElement = this._currentElement;
    this._currentElement = nextElement;

    this.updateChildren(nextElement.props.children, transaction, context);
  },
```

Lmk if I got it right and I'm happy to do the PR.

**Comment by iamdustan** [comment]
That sounds legit to me. I think the React version in package.json should be pinned explicitly.

I started looking at this really briefly last week because of React 15.4.0 RCs. If you’re interested, see how much the world will change in React 15.4.0 here: https://github.com/iamdustan/tiny-react-renderer/pull/18

**Comment by iamdustan** [comment]
Closing since the stack version is no longer maintained.
